# Format goes like this
# def_config:
#   k: v
# config:
#   k: v

def_config: !include config/algs/sp_mi/default.yaml

runner: StepsRunner
n_iter: 2000
n_sp_ts: 10000
eval_interval: 500
z_dim: 4
discrim_coef: 10
epochs: 15
num_mb: 5
lr: 0.0005
ent_coef: 0.03
