# Format goes like this
# trainer_name:
#   k: v

name: one_step_matrix
n_conventions: 32
k: [32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1] # 8
payoffs: np.ones(n_conventions) # np.linspace(1.0,0.5,n_conventions)
