# Format goes like this
# trainer_name:
#   k: v

name: overcooked
mode: full_divider_salad_4
horizon: 200
recipes: ["LettuceSalad",
            "TomatoSalad",
            "TomatoLettuceSalad",
            "TomatoCarrotSalad",
            "ChoppedCarrot",
            "ChoppedOnion"
          ]
obs_spaces: dense
num_agents: 2
interact_reward: 0.5
progress_reward: 1.0
complete_reward: 10.0
step_cost: 0.05
