# Format goes like this
# def_config:
#   k: v
# config:
#   k: v
def_config: !include config/algs/default.yaml

algo_name: incompat # used for creating a save directory
trainer: incompat
runner: EpisodesRunner
agent_name: IncompatMAPPOZ
render: True
render_only_sp: True
render_mode: 'rgb_array'
eval_interval: 50
n_eval_ep: 10
num_cpus: 1
use_gpu: False
debug: False
flatten_traj: False
training_device: cuda

parent_only: False
eval_all_pairs: True
n_iter: 400
num_xp_pair_sample: 1000 # sample all pairs by default
eval_interval: 50
n_sp_episodes: 50
n_xp_episodes: 50
n_sp_ts: 5000
n_xp_ts: 5000
n_eval_ep: 10
z_dim: 4
z_discrete: True
pop_size: 2
flatten_traj: False

lr: 0.0001
use_hypernet: False
pg_xp_max_only: True
value_xp_max_only: False
xp_coef: 1.0
discrim_coef: 0.1
gamma: 0.99
gae_lambda: 0.95
ent_coef: 0.03
clip_param: 0.3
vf_clip_param: 10
vf_coef: 1.0 # 0.5
num_mb: 5
mb_size: 0
epochs: 3
env_wrappers: [ZWrapper, AgentIDWrapper, StateWrapper]
shared_z: False
use_bandit: False
bandit_eps: 0.1
bandit_window_size: 3
uniform_selector_keep_last: False

anneal_xp: False
xp_coef_stop: 0.1
xp_coef_start: 0.0
n_anneal_iter: 1000
