# Format goes like this
# def_config:
#   k: v
# config:
#   k: v

def_config: !include config/algs/incompat/default.yaml

render: False
eval_all_pairs: False
get_act_dist: True
n_iter: 300
eval_interval: 300
n_sp_episodes: 100
n_xp_episodes: 100
pop_size: 32
z_dim: 8
lr: 0.0003
ent_coef: 0.0
discrim_coef: 0.0
xp_coef: 1.0
num_xp_pair_sample: 32
num_mb: 2
epochs: 10
