def_config: !include config/algs/maven/default.yaml

lr: 0.0005
z_dim: 4
n_iter: 30000
n_sp_episodes: 8
eval_interval: 10000
discrim_coef: 0.1
gamma: 0.99
start_e: 1
end_e: 0.05
explore_decay_ts: 1000000
