def_config: !include config/algs/maven/default.yaml

lr: 0.0003
z_dim: 4
n_iter: 1000
n_sp_episodes: 15
eval_interval: 1000
discrim_coef: 0.1
gamma: 0.99
start_e: 1
end_e: 0.05
explore_decay_ts: 200000
